Revert loading the data-readers
Apparently this causes an exception in boot (precisely the system this
fix was for).
clojure-emacs/cider#1462 remains open.

Exception message: https://clojurians.slack.com/archives/cider/p1455501034000003

    ERROR: Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :session f10681b1-e8f4-48c6-bbc9-869f5ec1d54a, :id 7}
    java.lang.IllegalStateException: Can't set!: *data-readers* from non-binding thread